### ISSUE TITLE
Wallet hangs/Unable to pay using Blockstream LN store payment request

### ISSUE THREAD

**Issue by jchello** [LN-Zap/zap-desktop#1166]
Mac OSX 10.13.6 using latest desktop version of Zap Version 0.3.1-beta (0.3.1-beta.5049) through my remote node. 

I am able to process Yalls payments just fine but when clicking through on the Blockstream store with the provided LN link the Zap wallet comes up and highlights green with a valid LN address however the payment screen and pay button does not immediately follow, as per normal. 

No action by the user is possible at this point except for closing the payment screen. 

![screen shot 2018-12-22 at 11 16 15 am](https://user-images.githubusercontent.com/9296962/50376982-103e3600-05db-11e9-8723-0a02ae09c441.png)

**Comment by mrfelton** [comment]
Thanks for reporting @jchello . This is caused by a limitation in the bolt11 library which we use to parse ln payment requests. The issue was resolved upstream in https://github.com/bitcoinjs/bolt11/issues/9 and I have a patch to merge those changes into our codebase waiting for review in https://github.com/LN-Zap/zap-desktop/pull/1167.
