### ISSUE TITLE
Consider using TypeScript

### ISSUE THREAD

**Issue by bolatovumar** [LN-Zap/zap-desktop#1213]
[TypeScript](https://www.typescriptlang.org) advertises itself as "Javascript that scales".

I have been using it at work for the past three years and couldn't recommend it enough. Quite a few large companies have adopted it for their applications (Slack, VSCode, HootSuite, a bunch of others...). I find that it helps tremendously with catching simple bugs so they don't even make it into the build in the first place. It also makes refactoring a breeze. IDE support for it is excellent. Linting ecosystem is great. I can go on and go on about how great it is really.

I see the project already uses Flow to some degree but it's becoming very clear that Flow has been losing to TS in a big way for the past several years. Very few people outside of Facebook seem to be using it and as a result the ecosystem is not as rich.

I understand that switching to TS in one go is a big undertaking but it can be done gradually. It supports even plan .js files so there is no need to jump into .ts-land right away. It also has quite a few compiler options that allow you to configure it to your liking. You can start with loose rules at first and make them stricter as you go.

You may still not want to switch to it at this stage of the project but it's something worth keeping in mind.

**Comment by mrfelton** [comment]
@bolatovumar  As you noted, this project makes very limited use of Flow currently. Where it has been used, it has brought a lot of benefit and I'd be keen to see this type of thing integrated much more deeply across the project as a whole.

As for Flow vs TS - I don't have a huge amount of experience with either, but my thinking about which is a better fit moving forwards pretty much mirrors your own for many of the reasons that you have mentioned.

A nice initial patch to get the ball rolling on this might be to replace everything todo with Flow, for it's Typescript equivalent, in all of the the places where it has been used across the codebase so that we can fully replace Flow with TypeScript from the onset (Would like to avoid having both Flow and TS active at once). So the initial scope would be pretty much limited to updating the tooling itself, and the code in `lib/lnd/config` and the few places where that lib is used.

From there, we could start to incrementally built TS support into other parts of the app as and when it makes sense.

**Comment by mrfelton** [comment]
My preference would be to use babel for transpiring as we currently depend on this quite heavily and there are some nuances with the setup. Keeping the changeset minimal would be ideal.

**Comment by bolatovumar** [comment]
@mrfelton I started working on this in my local branch and I'm using Babel's built-in TS preset. It seems to be the easiest way to integrate TS considering the heavy usage of Babel in this project.

It's quite a hefty undertaking but a good way to learn the codebase and discover a bunch of smaller issues.

**Comment by mrfelton** [comment]
Closing this issue since basic typescript support has been added already through https://github.com/LN-Zap/zap-desktop/pull/3461

Rather than leveraging typescript directly in the project we're documenting our type info exclusivly using jsdoc (which we already have implemented fairly comprehensively across the project). IMO this gives us the best of both words - great typescript/intellisense support with pure native js.
