### ISSUE TITLE
Not able to open new channel with node that has already opened channel with me.

### ISSUE THREAD

**Issue by themickeyc** [LN-Zap/zap-desktop#1575]
Someone opened a channel with me and I am trying to open back, but when I click "open channel" and type in their name or node address, it just says "connected" and doesn't let me open a channel back.

![screen shot 2019-02-14 at 8 34 17 am](https://user-images.githubusercontent.com/41479075/52790083-a28b1500-3033-11e9-894a-d6c614c90fdd.png)
![screen shot 2019-02-14 at 8 30 29 am](https://user-images.githubusercontent.com/41479075/52790084-a28b1500-3033-11e9-9a27-1bf1b8d7a31a.png)

**Comment by mrfelton** [comment]
Hi @themickeyc the current channel UI has several issues like this and we are activly working on a completely new UI that we hope will provide a much better channel management experience.

In the current version of the app however, it is possible to open multiple channels to a node that you already have channels with. It's just not intuitive for to do it. Try this:

Instead of pasting the address of node that you want to connect to in the search bar, just type some random string that returns no search results, eg `aaaaaaaa`. You will see a message saying that no nodes were found and button to `connect manually`. If you click that button, you will access a form which you can paste the node address into and connect from there!
