### ISSUE TITLE
Allow custom lnd configuration

### ISSUE THREAD

**Issue by JukeboxRhino** [LN-Zap/zap-desktop#167]
Allowing for custom configuration would allow users to

- Listen on custom ports for p2p connections, rpc and the REST server.
- Increase the maximum number of pending incoming channels per peer
- Enable/disable autopilot to allow users to run Zap without having it open channels for them, potentially locking up funds they would prefer remain off the lightning network

There are quite a few other configuration options, but these are the ones I feel are most important for users. If this were to be implemented into the GUI, these are the only options I would let users change.

**Comment by JimmyMow** [comment]
Nice, I think this would be cool. Gonna assign this to myself

**Comment by sneurlax** [comment]
You can use Zap for Litecoin's Lightning Network by changing some parameters...  If you consider extending generic support, I know that Decred and Vertcoin are both compatible (they all ultimately use `btcd`.)

**Comment by JimmyMow** [comment]
@sneurlax other currencies would need to add LND support. 

And then ultimately if they would like to have Zap production builds with all dependencies packaged in they would need neutrino support as well, which even LTC doesn't have.

I am down to support any coin though

**Comment by mrfelton** [comment]
We do now support custom lnd connections as well as configuration of key settings such as autopilot and node alias. We may look to add additional configuration options in the future.

I'm going to close this issue but If there are any further settings that you think should be added please open a new issue for each one individually so that we can discuss the specifics. Thanks.
