### ISSUE TITLE
Include invoice memo in payment detail modal

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#1838]
Currently, in our payment modal, we show the amount, current value date sent and preimage. Users have been trying to access the memo of the payment within' Zap and requesting this be added via Twitter.

I suggest the invoice memo be added below the current value and above the date sent:

<img width="955" alt="Screen Shot 2019-03-17 at 2 57 30 PM" src="https://user-images.githubusercontent.com/4040039/54497147-4bdc5980-48c5-11e9-9dd3-3cb3d3eb4373.png">

**Comment by mrfelton** [comment]
@JimmyMow  The memo comes from the invoice, but when you make a payment, lnd does not store the invoice that it relates to.

When we pull payments back from `listPayments`, the `payment_request` is not included so we have no way to extract the memo.

I think the only way to do it would be if we kept our own database of paid invoices, but that wouldn't be great since we would only know about invoices that were paid from Zap, and would not have that data for payments initiated via other means

**Comment by JimmyMow** [comment]
Ok makes sense. Going to close this for now then
