### ISSUE TITLE
close channel while LNBIG[1] offline but the btc never return after 1000 block mined, transaction shown 0 btc send.

### ISSUE THREAD

**Issue by kai-btc** [LN-Zap/zap-desktop#1896]
btc disappear after close channel

## Description

by 19/3, LN big[1] have offline for two days and i decided to force close the channel with block 567733 and transaction ID-644d335e4433c424acdca99b38baf8e7f24ad078cdbaa0e9f68a65d84fd91eb5 as this shown the btc  have send to the old address which is keep changing every time  sending to wallet.

## Expected Behavior
btc returned as usual to my node

## Actual Behavior

btc never return after 1000 block have been mine

## Your Environment

- Zap version:latest version 
- Operating System and version:window 8.

**Comment by kai-btc** [comment]
![Screenshot (13)](https://user-images.githubusercontent.com/48932673/55067715-2ae0e900-50bb-11e9-9eb8-b538643f9c4b.png)
![Screenshot (12)](https://user-images.githubusercontent.com/48932673/55067717-2c121600-50bb-11e9-817d-5df784f91c25.png)
![Screenshot (14)](https://user-images.githubusercontent.com/48932673/55067722-2d434300-50bb-11e9-935e-ed1d77642f3b.png)
### attach screenshot with the wallet address and transaction id

**Comment by mrfelton** [comment]
@kai-btc it is normal that you wallet address changes after every transaction to/from it. All bitcoin wallets work this way.

When you force close a transaction it does take some time before you receive the funds. In the latest version of Zap we show this as `blocks til maturity` in the UI (which you can see on the channel detail page).

Also, older versions of lnd had some issues with the force close behavoir. For example, see:

 - https://github.com/lightningnetwork/lnd/issues/895
 - https://github.com/lightningnetwork/lnd/issues/2948
 - https://github.com/lightningnetwork/lnd/issues/1571

You screenshot looks like a very old version of Zap. I would suggest that you upgrade to the latest version.

Since the issue here is related to lnd, I'm going to close the issue as there is not a lot we can do about this. I would suggest that you ask in the lnd slack and/or in their github.
