### ISSUE TITLE
Unable to connect iPhone to lnd node from Node Launcher via Zap Desktop QR Code

### ISSUE THREAD

**Issue by themickeyc** [LN-Zap/zap-desktop#1905]
## Description

My zap desktop is running on Mac, channels open, working fine. I have the latest versions running on Mac and iOS.

I generate the QR code for LNDConnect, scan it with my iPhone, but I always get the error. Could not connect to server. (Connect Failed)

## Expected Behavior

I expect my iPhone app to be able to connect to the desktop with lndconnect

## Actual Behavior

I get the error "Could not connect to server. (Connect Failed)"

## Possible Fix

something is wrong with lnd.conf or another file with the wrong IP address, maybe?

## Context

I want to use lightning on my iPhone, but it won't connect

## Your Environment

MacBook Pro and iPhone x running on the same wifi network

- Zap version: 0.4.0 and 0.1.0
- Operating System and version: Mac and iPhone

**Comment by mrfelton** [comment]
We worked through this issue in Slack. The problem is that the Node Launcher initiates the connection to Zap using the IP address `127.0.0.1` which is not accessible from the iPhone.

In order to connect the phone, lnd must be exposed on an external address, and the connection from Zap Desktop must use that external ip address.
