### ISSUE TITLE
Balance not appearing

### ISSUE THREAD

**Issue by Maghferat** [LN-Zap/zap-desktop#1969]
Balance not appearing on Zap 0.4.0 Beta after I closed my Zap Wallet and after wallet recovery also!!

**Comment by Maghferat** [comment]
tried many times to recover my wallet with my seed but still shows zero balance and no more old transactions! ( run win 7 and instlled the latest Zap ver. 
any suggestion

**Comment by mrfelton** [comment]
Was your wallet balance in a standard onchain address or in Lightning channels?

**Comment by Maghferat** [comment]
that was in standard onchain address

**Comment by Maghferat** [comment]
35hqWLQTQDHfP5x5xbxFa4oimyBJR9Fz3D

**Comment by JimmyMow** [comment]
@Maghferat how were you using Zap? Connecting to a remote node or did you create your wallet with Zap?

**Comment by Maghferat** [comment]
I created my wallet with zap and all my seeds are available for me but if I
try to recover it, no way:(

JimmyMow <notifications@github.com> schrieb am So. 7. Apr. 2019 um 21:51:

**Comment by Maghferat** [comment]
Zap Wallet stick in Fetching tickers since 24h !!!

**Comment by JimmyMow** [comment]
@Maghferat how did you get to the fetching filters screen? After trying to log into your wallet or after trying to recover?

Also, are you still on the machine that you originally sent the BTC to? Why are you recovering the wallet?

**Comment by Maghferat** [comment]
After I transferred some Bitcoin in zap wallet, I tried to connect my node
to lightning power users, but it was not successful and after that I
restart Zap then I couldn’t connect any more. I’ve tried many different
ways and if I recovered with last seeds the balance was zero without any
transaction tree!
I am still on the same machine that I originally sent the btc to! I am
since 24h trying to connect to my node but no way:(

JimmyMow <notifications@github.com> schrieb am Mo. 8. Apr. 2019 um 07:43:

**Comment by Maghferat** [comment]
how did i get to the fetching filters screen? After trying to log into my
node

Saeed Maghferat <bitcoin.maghferat@gmail.com> schrieb am Mo. 8. Apr. 2019
um 07:54:

**Comment by Maghferat** [comment]
could anyone please help with fetching filters screen?

**Comment by nycnikato** [comment]
This same issue is happening for me as well. Onchain balance and activities not showing.

**Comment by Maghferat** [comment]
after i Installed th enew version of Pierre's LND Launcher, installed also the new version of Zap. all the connections work ok, only my balance shows still zero:( after many back and force with Pierre, it sounds to him that neither Zap's LND instance nor the default LND instance have received funds.
my funds is in this address:

35hqWLQTQDHfP5x5xbxFa4oimyBJR9Fz3D

also i used my seeds to recover the previous zap wallet but it shows not only zero balance but also the different BTC Addresses!!
Pierre mentioned also Zap has created its own LN node + wallet, separate from the standard LND one which the Node Launcher uses. the Node Launcher does not delete the LND data directory.

i am using Zap since months and i transferred many times.
but now i see my funds in blockchain looking at me dependable:

Conclution: I lost my funds and if you want to be safe, don't use Zap anymore!
I have recieved no reply from Zap, since my last issue also from Slack-Zap.

**Comment by nycnikato** [comment]
You are correct. Zap is essenially unusable. They created a wallet system which is not compatible even with eclair.

**Comment by mrfelton** [comment]
Sorry you guys are having some issues with this. This might be easier to try to debug in Slak, so please hop over there and ping me.

Let me try to clarify a few things though as it sounds like there may be some confusion here as to what Zap is and how it works. Zap can be run in 2 different modes:

**1) By connecting to your own EXTERNAL lnd node**: In this mode, you create your own lnd node in what ever way that you want, such as by using the node launcher, and then you connect Zap to this node. In this mode Zap is literally a UI and remote control for that node. All data that gets displayed inside Zap comes directly from that node. We don't store any data locally (other than your node's connection details).

**2) By using the INTERNAL lnd node that we bundle with Zap**: In this mode, we create and run the lnd node for you, directly inside Zap, and then connect to that node and allow you to remote control it from the Zap UI. This is literally the same lnd binary that the Node Launcher uses (although it may be a different version). There is no custom lnd implementation - it is lnd from Lightning Labs. This mode is experimental as it runs lnd in Neutrino mode (ie, as a lite client).

If you are using Zap to restore a wallet from a seed, this will use mode (2) from above - it will create a new wallet using your existing seed and launch that wallet as a Neutrino lite client. Any funds that are in on-chain addresses associated with that seed should be restored into a new lnd wallet instance. This is handled directly by lnd.


> also i used my seeds to recover the previous zap wallet but it shows not only zero balance but also the different BTC Addresses!!

After restoring a wallet into Zap, a new address will be generated, just as every time you make or receive a transaction, a new address is generated. The wallet and address management happens inside lnd and so any balance from addresses associated with your seed should be picked up by lnd in the recovery process, and therefore be visible within Zap.

When we import the seed into lnd, we set the recovery window to 250. If your wallet has generated more than 250 addresses, funds from older addresses will not be included. in lnd 0.6.0 they have increased the default from 250 to 2500, and in our next release we will also be increasing this value.

> Zap is essentially unusable. They created a wallet system which is not compatible even with eclair.

Zap literally is a UI for lnd. If lnd is compatible with eclair - which I believe it is - then so is Zap by proxy.

> could anyone please help with fetching filters screen?

If you could provide a screenshot, it would help us to understand where exactly Zap is stuck. Though it sounds like your are using the Neutrino light client, which is still experimental and has some issues when it comes to the sync process. Often just restarting the app and trying again is enough to get past this (this will trigger us to stop and restart the lnd instance, which often gets it going again).

Alternatively, if you are seeing the loading screen whilst trying to connect to an external node, it could be that the version of lnd that you are connect to is incompatible with Zap. `Zap 0.4.0` is not compatible with `lnd v0.6.0-beta` and this was a known issue that was resolved in `Zap 0.4.1`. Please ensure that you are using the Zap 0.4.1 release. See https://github.com/LN-Zap/zap-desktop/issues/1966 for more info.

> Conclusion: I lost my funds and if you want to be safe

If you do indeed still have the seed, and your funds were in on-chain addresses and not in lightning channels, then you should be able to recover them into any lnd instance. Ping me in Slack if you would like further help with this.

Anyway... it's a little hard to debug what's actually going on here, because there are now multiple different and scenarios and potential issues being discussed, which may or may not be connected. This would be a lot easier to debug in Slack.

**Comment by Maghferat** [comment]
After I tried to debug in slack but no reply since days, I tried to explain my issue in this platform!

Send from my iPhone

**Comment by mrfelton** [comment]
@Maghferat there are a bunch of us that hang out in Slack and try to help people through issues like this. Try again  - I guess your messages fell through the net.

**Comment by mrfelton** [comment]
@Maghferat I'm going to close this issue since we have spoken extensively about your problems on Slack. In summary, this comes down to a couple of different issues.

1) The reason why the balance was showing as 0 is because you created 2 seeds, you didn't know which one was the one that you send funds to, and you imported the one that never had funds sent to it.

2) The other seed that you tried to import was encrypted when you created it using the Node Launcher app. Zap does not currently support importing encrypted seeds. There is an issue to add support for importing encrypted seeds here https://github.com/LN-Zap/zap-desktop/issues/2071. Until we have that support in Zap, you can import this directly into lnd (you will need to know the passphrase that you used when you created/encrypted the seed - the one you provided me in slack is incorrect)
