### ISSUE TITLE
ZAP desktop mainnet: open channel to Eclair

### ISSUE THREAD

**Issue by wdey** [LN-Zap/zap-desktop#1986]
I assume it's correct, that autopilot doesn't show up if connecting to mainnet.
I cannot create a channel to a Eclair node. Entering a valid public key gives NO RESULT, although I can find my node on 1ML.com; and I can't find any other option.

**Comment by mrfelton** [comment]
> Is ZAP requesting a minimum of 1 mBTC channel capacity ?

The channel size restrictions are defined by the nodes that you are trying to connect to.

> What happens if my Internet IP Address changes (my provider doesn't give me a permanent one)

This probably depends on how you have your node configured. Lnd does have some support for NAT and I believe there has been some work done to make it dynamically update and rebroadcast your IP address if it changes, though I don't know the status of that. If you have set `externalIp` manually, I think you may need to update the setting manually and restart your node. If your node's IP address changes I think it will rebroadcast it's updated IP address to the network so that other peers become aware of the changes.

> I see that the channel has remote blance of 0, therefore I cannot receive anything ? Could I configure a bidirectional channel upon initial setup ?

No. This is not supported currently. The BOLT 1.1 spec will likely be introducing bi-directional payment channels.

> will channel close reverse the fund to my ZAP node ?

If you close a channel, funds allocated to you from the channel balance will be sent back to one of your on-chain wallet addresses.
