### ISSUE TITLE
ZAP: private channel

### ISSUE THREAD

**Issue by wdey** [LN-Zap/zap-desktop#2007]
Is it correct, that ZAP initiated channels are private ones; at least I don't see them counting on a Eclair node, resp. displayed in 1ML.com.
Is it correct that autopilot is by default running, also if connected to mainnet (I was never asked ?)

**Comment by mrfelton** [comment]
@wdey 

If you are using the internal lnd neutrino client, then yes - all channels that we open are private channels since your node is not going to be a routing node. If you connected to Mainnet, then autopilot is off by default since it's not currently recommended to use on Mainnet. You can however turn it on by logging out of your wallet and editing the autopilot settings on the wallet setting screen.
