### ISSUE TITLE
There was a problem sending your payment. FinalExpiryTooSoon - 23 satoshis

### ISSUE THREAD

**Issue by wdey** [LN-Zap/zap-desktop#2074]
There was a problem sending your payment. FinalExpiryTooSoon
- 23 satoshis
Can someone clarify what this message means exactly, resp. how to fix it.

**Comment by mrfelton** [comment]
Hi @wdey .

This error comes directly from lnd and happens when the last HTLC of a route (exit hop) has an expiration height that is deemed too soon by the final destination of the HTLC.

`if lastHtlc.cltvExpiry < expectedHeight`.

See https://github.com/lightningnetwork/lnd/blob/42c45979215e3242ef2e162ccd9de3cbb0ed28a1/htlcswitch/link.go#L2286-L2300 for implementation details.
