### ISSUE TITLE
Error on deb package: Invalid cross-device link

### ISSUE THREAD

**Issue by alganza** [LN-Zap/zap-desktop#2089]
## Description

Error "Invalid cross-device link" while installing deb package:

dpkg: error processing archive Zap-linux-amd64-v0.4.1-beta.deb (--install):
error creating hard link './usr/share/icons/hicolor/0x0/apps/zap-desktop.png': Invalid cross-device link

## Expected Behavior

It should install the wallet.

## Actual Behavior

It does not.

## Possible Fix

Keeping everything under the same path /usr/local/ or /opt/, maybe?
I don't understand why a program installed on /opt/ or /usr/local/ needs to fiddle with /usr/share/.

## Steps to Reproduce

- 1. dpkg -i Zap-linux-amd64-v0.4.1-beta.deb with /opt/, /usr/local/ and /usr/ on different filesystems. Actually, I use different btrfs subvolumes.

- 2.
- 3.
- 4.

## Context

I'm trying to install Zap Desktop wallet 0.4.1, so that I can run a LN LTC node, apart from the BTC one.

## Your Environment

Devuan, with btrfs subvolumes for /, /var/, /var/tmp/, /opt/, /srv/, /usr/local/...

- Zap version:
- Operating System and version:

Devuan (deb package) ascii.

**Comment by mrfelton** [comment]
@alganza can you elaborate on the issue please?

**Comment by alganza** [comment]
What can I elaborate on?  I posted all the information I can gather, I believe. Installing the deb package tries to create a hard link between two different locations (/usr/ and /opt/, I believe) which is reasonable to want to keep under different disk partitions or, as in my case, on two different btrfs subvolumes.

**Comment by mrfelton** [comment]
@alganza sorry, the email notification I received from your original post was incomplete. Thanks for the info.

We rely on [`electron-builder`](https://github.com/electron-userland/electron-builder) for packaging the app and the issue that you have noted might be better to raise with their team directly.

Is there any reason why you are using the `.deb` rather than the `.Appimage` portable build?

Also note that in the future we will likely ditch the `.deb` build all together in favour of a better supported and more universal format such as Flatpak. For now though, the Appimage has a number of advantages over the `.deb` and I would recommend that you use this instead.

**Comment by alganza** [comment]
Thank you for your answer.
Sure, I'd use an AppImage if you provided one for amd65.

**Comment by alganza** [comment]
I tried the 86_64 AppImage and it worked. I assumed that image was for the IA86 processors, and not for the amd64. It's working fine on my box. Thank you.

**Comment by mrfelton** [comment]
Great!
