### ISSUE TITLE
Payment Send loops (connecting to Eclair)

### ISSUE THREAD

**Issue by wdey** [LN-Zap/zap-desktop#2145]
Payment request ZAP to Eclair LN full node. ZAP has one open channel to LightingTo.Me.
Up to date version for ZAP and Eclair.
Command loops and after long wait I receive
**There was a problem sending your payment. Payment attempt not completed before timeout of 1m0s**
Where can I find additional information ?

**Comment by mrfelton** [comment]
@wdey this error comes directly from lnd. It typically means that a suitable path to your destination has not been found within a minute, after which they time out the payment attempt.

**Comment by wdey** [comment]
Something is really strange
1) I have a 2 hop Connection (channel) from ZAP via X to Eclair full node
2) Create a invoice on Eclair, entering pay command in ZAP: ZAP searches for routes, and seems to find, entering fee: between 1 and 2 sat
3) how does multipathing work in ZAP ? eg. 2 channels for redundancy ? eg. if first channel fails, tries send one; and who is the first one ?
4) I would really like a tool like "ping" and "traceroute" we have for IP networking !
Just to be clear; I don't blame ZAP for my Problem; most likely it's either a Eclair and/or interop issue !

**Comment by mrfelton** [comment]
To answer your questions:

> how does multipathing work in ZAP ? eg. 2 channels for redundancy ? eg. if first channel fails, tries send one; and who is the first one ?

Zap is mostly just a UI for lnd. So, we just use lnd's api and ask it to pay the invoice using the (`sendPayment`](https://api.lightning.community/#sendpayment) command. If the payment attempt fails, we wait for a couple of seconds and try again, up to 3 times incase of a temporary routing issue.

Regarding the issue itself - it's an lnd routing issue so a little outside of the scope of Zap. My suggestion would be just to always make sure that you are running the latest version of Zap and Lnd. Routing is a known pain point and hopefully this will improve over time.

One thing worth noting is that we have just fixed a bug in which Zap would try to snd a payment with the maxFee set to zero sometimes, which w believe was causing some payments to fail. This issue has been fixed in https://github.com/LN-Zap/zap-desktop/pull/2575 and will be included in 0.5.1 so be sure to update to 0.5.1 once we release it in the coming days.
