### ISSUE TITLE
IPv6 lnconnect string not displayed correctly

### ISSUE THREAD

**Issue by sohomangue** [LN-Zap/zap-desktop#2172]
## Description
While connecting for the first time to a node, trying to use a connection string that contains an IPv6 address cuts it on the UI. 

## Expected Behavior

The host address and port should be displayed in its full form (e.g. "[2a01:e34:vru2:8351:1334:c421:23a2:vab9]:10009").

## Actual Behavior

Only the part preceding the ":" character is displayed: "[2a01" (see screenshot below).

## Possible Fix

Don't cut the IP string to the first ":" char.

## Possible additional issue

If the code in charge of decomposing the connection string actually stops at the first ":" char, it could be impossible for people on IPv6-only networks to connect to their nodes. I haven't checked if that's the cas though, as I only have IPv4.

## Your Environment

- Zap version: 0.4.1-beta
- Operating System and version: macOS Mojave 10.14.4

<img width="924" alt="Screenshot 2019-05-08 at 02 33 11" src="https://user-images.githubusercontent.com/28465517/57341310-30116900-713a-11e9-941d-684c5f8afaa9.png">

**Comment by mrfelton** [comment]
Thanks for the report @sohomangue .

The host string is only truncated for display purposes. The intention is to remove the port part so that we displaying the info that the user most cares about - what host they are connecting to. When we initiate the connection we use the full host/port string.

We will look to fix this so that the display better handles IPv6.

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/2287
