### ISSUE TITLE
Loading BTC doesn't show up

### ISSUE THREAD

**Issue by wdey** [LN-Zap/zap-desktop#2185]
After my recent trouble, I started from scratch. sending some BTC to the address shown in the ZAP wallet: 3BDaeqrxa1q9S8YozSuTwerbXkYtVJon4i

I watched the tx, which got >3 confirmations , but my balance is still 0 sat.

I verified the tx, and the receiving address is correct
3BDaeqrxa1q9S8YozSuTwerbXkYtVJon4i

ps. I can send you per email a screenshot of the wallet, showing BTC address and QR and the tx-id

**Comment by mrfelton** [comment]
I just did a test and can't reproduce this issue. This is what I did:

1. Open `Zap 0.4.1`
2. Click `Create`
3. Write down seed
4. Enter 3 seed words to confirm
5. Enter a wallet name
6. Select`Mainnet` option
7. Send money to the address shown on the syncing screen
8. Wait for about 3 minutes for it to finish syncing (It was slow for me because I'm on a mobile hotspot)
9. Wallet opens and shows 0 for the balance (transaction is still unconfirmed)
10. Wait for a few minutes for transaction to 1 confirm on the blockchain
11. ... As soon as the transaction is confirmed on the blockchain, I get a desktop notification from Zap telling me I received a transaction, I check Zap, and the balance now show correctly in Zap.

Is this the same as the steps you took? What am I missing?

Are you sure you send to the correct address? Maybe you have some malware on your machine that is messing with your clipboard and making you send to the wrong address?

If you click on the QR code in Zap to view your wallet address, is it showing you the same address that it did originally - the address that you sent money to?

**Comment by wdey** [comment]
I deinstalled / installed everything, and then exactly 1..10.
Then I sent some BTC from Exodus to the BTC address of ZAP. (I used the copy address into the clipboard, and paste it to Exodus send command).
**Important Exodus and ZAP run on 2 different servers; I control everything by means of a TeamViever session.**
Result: even after 3 confirmations: 0 sat
My servers are clean, and the QR code and clipboard address are identical.

I sent some BTC from my BlueWallet using same address as above! but this time using QR code.
Result: it works ! Porga miseria !

I can hardly believe, that the clipboard adds/appends non printable characters or is it a Exodus Wallet issue ?
Have you an explanation ?

**Comment by mrfelton** [comment]
@wdey so, let me be clear:

You send bitcoin from 2 different wallets (Exodus and Blue Wallet) to a single address provided by Zap. The money sent from Blue Wallet arrived and is visible in Zap, but the money sent from Exodus is not.

If you look up that address on the block explorer does it show both transactions as received?

Can you provide the bitcoin address that you sent the coins to?

**Comment by wdey** [comment]
Exodus tx  https://blockstream.info/tx/7e35b8d0c2f0d4944556fa3cf6345e0d3bac98e8b9182bd7c4563ec8915e2052

Pointer is the ZAP address

[cid:image001.png@01D50781.E1E27CF0]

BlueWallet tx : https://live.blockcypher.com/btc/tx/4fc67e6c79af05ed95bc615cb8572e6321bfbc7e512ec021151ee885090b7f2b/

[cid:image002.png@01D50782.5FC11550]

Btw. I did a 3. Tx, from BTC Core wallet to ZAP which was ok as well.

Cheers
Walter.

Von: Tom Kirkpatrick <notifications@github.com>
Gesendet: Freitag, 10. Mai 2019 21:36
An: LN-Zap/zap-desktop <zap-desktop@noreply.github.com>
Cc: wdey <wdey@bluewin.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [LN-Zap/zap-desktop] Loading BTC doesn't show up (#2185)


@wdey<https://github.com/wdey> so, let me be clear:

You send bitcoin from 2 different wallets (Exodus and Blue Wallet) to a single address provided by Zap. The money sent from Blue Wallet arrived and is visible in Zap, but the money sent from Exodus is not.

If you look up that address on the block explorer does it show both transactions as received?

Can you provide the bitcoin address that you sent the coins to?

**Comment by mrfelton** [comment]
Very strange. I have no idea why this would be.

I would suggest that you ask the lnd guys in their slack room. This really has little to do with Zap itself - all we do is provide a UI on top of lnd. The transaction isn't showing in lnd. It seems as if lnd isn't registering the Exodus transaction for some reason.

If you run `lncli listchaintxns` and `lncli listunspent` you will see exactly the same data as what you you see in zap (we literally call `listchaintxns` via the gRPC interface in order to get the list of transactions that we show).

**Comment by wdey** [comment]
I see the following:

The Exodus tx has 1 input and 2 outputs: the return address has Bech32 format.

BluWallet tx has 1 input and 1 output

Both tx are on-chain ! and working ! has lnd api a problem with Beach32 format ?

Von: Tom Kirkpatrick <notifications@github.com>
Gesendet: Samstag, 11. Mai 2019 07:22
An: LN-Zap/zap-desktop <zap-desktop@noreply.github.com>
Cc: wdey <wdey@bluewin.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [LN-Zap/zap-desktop] Loading BTC doesn't show up (#2185)


Very strange. I have no idea why this would be.

I would suggest that you ask the lnd guys in their slack room. This really has little to do with Zap itself - all we do is provide a UI on top of lnd. The transaction isn't showing in lnd. It seems as if lnd isn't registering the Exodus transaction for some reason.

If you run lncli listchaintxns and lncli listunspent you will see exactly the same data as what you you see in zap (we literally call listchaintxns via the gRPC interface in order to get the list of transactions that we show).

**Comment by mrfelton** [comment]
@wdey I'm glad you have it working at least and that it seems that there isn't a bug in Zap that's causing issues. It is strange though and I can't really explain the behaviour you were seeing.

It's worth noting that when you are using Zap in this way you are running lnd as a Neutrino lite client, which is very experimental and we don't consider it to be production ready yet (this is why we label using mainnet with a warning when creating the wallet). So it';s possible that there is some kind of neutrino related bug at play here.

Our next release will include updates to a more recent version of Neutrino.
