### ISSUE TITLE
What is my host and port - I'm trying to open a channel?

### ISSUE THREAD

**Issue by marsrobertson** [LN-Zap/zap-desktop#2271]
I'm new to Lightning Network business.

I'm currently using BlueWallet on iOS.

As someone explained to me - they are custodial, they automatically open channels, `1000 sat` payment was possible.

Now I'd like to send some magic internet money to Zap.

![image](https://user-images.githubusercontent.com/44369284/58346029-bffd2580-7e51-11e9-98fe-9734765b2891.png)

# Tool for opening channels: https://ion.radar.tech/developers#channel-request

![image](https://user-images.githubusercontent.com/44369284/58345671-cc34b300-7e50-11e9-8826-d917c98385f8.png)

# What is my `host` and `port`?

**Comment by marsrobertson** [comment]
The other way round: https://ion.radar.tech/#node-connect

![image](https://user-images.githubusercontent.com/44369284/58353247-e62cc080-7e65-11e9-8df1-7ada7b051fa8.png)

**Comment by marsrobertson** [comment]
https://zaphq.slack.com/archives/C6P5UNJMV/p1558745749010600

https://thebitcoingames.slack.com/archives/CHPUE3CVA/p1558750524032900

> Then you likely won’t have a a static host ie your pc ip address is always changing unless you do some fancy config with your router and open ports etc

> However radar can technically open a channel to you but seems they don’t have the interface to let users without our a fixed public host/ip address to do that (it’s out if scope but if you ran over for you’d get a host without having to do fancy router config)

**Comment by mrfelton** [comment]
Currently when running Zap as a neutrino client your desktop node is not configured as a routing node and your IP address is not exposed.

If you instead connect Zap to your own lnd node which you have configured to expose the p2p port, setup firewall rules and port forwarding etc then you would be setup to handle incoming connections and Zap would show your IP address and port number.

I believe that lnd now has some UPnP support too so can explorer using this in order to figure out your external ip address and automatically configure your router.

We will likely look to add TOR support soon and there is already an issue for this: https://github.com/LN-Zap/zap-desktop/issues/2209.
