### ISSUE TITLE
Inconsistent display of on-chain balance

### ISSUE THREAD

**Issue by marsrobertson** [LN-Zap/zap-desktop#2277]
`0.4.1-beta`

Not using a template as image is self-explanatory:

![inconsistent 2019-05-26 10_34_19](https://user-images.githubusercontent.com/44369284/58379908-dadeaf80-7fa1-11e9-9db1-68324bffde98.gif)

**Comment by mrfelton** [comment]
Hi @marsrobertson , thanks for your report.

These are actually showing two different things by design, though maybe we need to find a way to make this more clear to users.

On the main wallet page we show your full balance including all onchain (confirmed and unconfirmed) and all offchain (in channels) balances.

On the Pay form we only show your current confirmed onchain balance since this is the only one that is relevant in the context of sending on-chain transactions (you can not send unconfirmed funds).

**Comment by marsrobertson** [comment]
After becoming more familiar with Lightning - the balance was inconsistent due to timelock.

See #2280 - my adventures using Zap.

Good technical article: https://blog.usejournal.com/the-bitcoin-lightning-network-a-technical-primer-d8e073f2a82f
