### ISSUE TITLE
Bug: MacOS UI missing FUND YOUR ZAP WALLET/Syncing stuck at 0%

### ISSUE THREAD

**Issue by floundies** [LN-Zap/zap-desktop#228]
After downloading mac-release-v0.1.0-beta.zip and unpacking the dmg on Mac OS 10.13.2, zap application is launched from the Applications directory. However, the Zap app doesn't have the bottom black bar that says FUND YOUR ZAP WALLET that's visible in the YouTube video. The Syncing stays at 0%. Uninstalled and reinstalled to no avail. Not sure if I missed a requirement for running/installing from the dmg.

Screenshot of Zap - fullscreen:
<img width="1440" alt="screen shot 2018-01-26 at 10 25 48 pm" src="https://user-images.githubusercontent.com/3433553/35468375-4c6c42c4-02ea-11e8-80c8-85e4837ba677.png">

Screenshot from Youtube:
<img width="883" alt="screen shot 2018-01-26 at 10 42 22 pm" src="https://user-images.githubusercontent.com/3433553/35468374-4c62c442-02ea-11e8-860c-1677bf9e22b7.png">

Thank you.

**Comment by d1gitalflow** [comment]
got the same problem but for windows 10.

**Comment by JimmyMow** [comment]
The "Fund your Zap wallet" was actually removed before release, sorry for the confusion with the YouTube videos.

It seems we have experienced way more traffic than we were expecting and overloaded a hard-coded node Zap is connecting to. 

This issue is actually a replica of #230 so I'm going to close this and let's take the conversation over there

**Comment by dasilvarosa** [comment]
I'd suggest adding an annotation on the YouTube video to specify it's not included in 0.1.0.
