### ISSUE TITLE
Allow customisation of fee 

### ISSUE THREAD

**Issue by marsrobertson** [LN-Zap/zap-desktop#2284]
Malta AI Blockchain: https://youtu.be/ubPhprQfQKE?t=23529

Tweet by Tone Vays: https://twitter.com/ToneVays/status/1132078743558582273

My favourite mempool stats:
* https://mempool.space/

(there are some really low `sat` transactions mined)

![image](https://user-images.githubusercontent.com/44369284/58415940-f1efd100-8077-11e9-8be0-2285574cfb96.png)

* https://jochen-hoenicke.de/queue/#1,1w

---

# Current user interface for opening channels

![image](https://user-images.githubusercontent.com/44369284/58415893-ccfb5e00-8077-11e9-9573-df92f51861e3.png)

This is ordes of magnitude higher than what is currently mined.

---

Related: https://github.com/LN-Zap/zap-desktop/issues/2099

**Comment by mrfelton** [comment]
In 0.4.1 / master branch the fees come from https://bitcoinfees.earn.com/api/v1/fees/recommended.

In the `next` branch this has been improved via https://github.com/LN-Zap/zap-desktop/issues/1972.

And in https://github.com/LN-Zap/zap-desktop/pull/2200 it has been made possible to customise these.

Closing as a duplicate

**Comment by marsrobertson** [comment]
Sorry about the duplicate.

The API seems not picking up the latest state of the mempool:

![image](https://user-images.githubusercontent.com/44369284/58557825-39609380-8217-11e9-87d8-06135d089749.png)

# blockchain.info
![image](https://user-images.githubusercontent.com/44369284/58557788-28b01d80-8217-11e9-87e3-049dda6a9552.png)

**Comment by mrfelton** [comment]
We aren't using that API any more. If you check out the `next` branch it now generates fees from https://bitcoinfees.earn.com/api/v1/fees/list using specific target confirmations.

We default to using the following target confs: `slow=6, medium=3, fast=1` and you can override these defaults to your likening on our new settings page (currently accessible from the wallet menu).

Also, if you are connected to your own lnd node it will actually use your own node's bitcoind backend api to generate the fee estimates instead of earn.com's api.

**Comment by marsrobertson** [comment]
Cool, cool, you've closed the issue and explained this is solved now.

I was just observing that API is not acting as expected.
