### ISSUE TITLE
Clicking a "lightning:" link opens a second Zap application rather than initiating a payment on the app already open

### ISSUE THREAD

**Issue by LeeWallisUK** [LN-Zap/zap-desktop#229]
## Description

Clicking a "lightning:" link opens a second Zap application rather than initiating a payment on the app already open

## Expected Behavior

Should focus the already open instance of zap and populate the payment form.

## Actual Behavior

Opens a second instance of the app.

## Possible Fix

https://electronjs.org/docs/api/app#apprequestsingleinstancelock

## Steps to Reproduce

1. Open Zap on Windows
2. Go to yalls.org and click the "Pay to continue reading" button on an article.
3. Click "Open Zap" when the dialog box appears.

## Your Environment

- Operating System and version: Windows

**Comment by LeeWallisUK** [comment]
1. Open Zap on Windows
2. Go to yalls.org and click the "Pay to continue reading" button on an article.
3. Click "Open Zap" when the dialog box appears.

**Comment by CryptoChronicus** [comment]
I can confirm, Starblocks does the same for me. I click "OPEN WITH YOUR WALLET" and it opens a 2nd instance of Zap, and does nothing, it doesnt even open the invoice so that I can pay for the coffee.

copying the payment request and attempting to pay it says it cannot find a route. I have 3 channels. I will wait and try more

**Comment by mrfelton** [comment]
Can you please confirm if you still have this problem with the latest release of Zap? I have not been able to reproduce the issue. Thanks.
