### ISSUE TITLE
(Mac) Can't install using .dmg-file

### ISSUE THREAD

**Issue by AdriaanVanNuffel** [LN-Zap/zap-desktop#232]
When trying the Zap-0.1.0.dmg file, my Mac tells me "Can't complete this action, because one or more necessary parts can't be found. (Errorcode -43)"

![schermafbeelding 2018-01-27 om 13 54 58](https://user-images.githubusercontent.com/35861589/35472146-eddc07d2-0369-11e8-943b-dfbf8ba092aa.png)

So I've unzipped zap-0.1.0-mac.zip and am running the Zap application from that zip.

**Comment by Empact** [comment]
This worked for me with the 0.1.1 and 0.1.0 releases, with Mac OS 10.13.3.

This page says this error code could be due to disk corruption, which fits the failure. Could you try running disk repair and trying again?

https://discussions.apple.com/thread/5388208
https://support.apple.com/en-us/HT201639

**Comment by Empact** [comment]
Closing as inactive. Presuming disk corruption was at fault. @AdriaanVanNuffel please reopen if that was not the case!
