### ISSUE TITLE
UX Suggestion: Filters for transactions

### ISSUE THREAD

**Issue by bitcoinuser** [LN-Zap/zap-desktop#250]
Hi, I really like ZAP design. So I would like to give a suggestion of how I would like to see filters for transactions be implemented.

1- Now Zap has a dropdown menu with five options: All Activity, Ln Activity, Ln Payments, Ln Invoices, On-Chain Activity.

2- I think should have only three options: All Activity, Ln Activity and On-Chain Activity.

3- I think should have buttons like this image. (See the buttons next all activity) 

![captura de tela de 2018-01-28 10-23-57](https://user-images.githubusercontent.com/1178856/35482478-228be962-041d-11e8-8f53-b3bd56d067c0.png)

4- The way I think ZAP should implement filters is something like what bread wallet has in their wallet. See the image:

![photo5145531143603464141](https://user-images.githubusercontent.com/1178856/35482504-9ecf6f62-041d-11e8-9a74-6ed8120ea251.jpg)

**Comment by lucaszanella** [comment]
Yes, for people that do a lot of invoices, would be great to monitor the ones pending

**Comment by bitcoinuser** [comment]
I like this format of button: 

![botao](https://user-images.githubusercontent.com/1178856/35511703-20e76024-04e4-11e8-9366-2d5e9cf21e38.jpg)

**Comment by bitcoinuser** [comment]
When we close a channel, I think the pending refund transaction should appear on transaction list. So I think it should exist a refund button on fillter too.

**Comment by odb366** [comment]
I think this is a great proposition to ditch the dropdown component and replace it with buttons (or the so called [radio groups](https://www.lukew.com/ff/entry.asp?1950)). Here's my pros/cons of both:

**Dropdown advantages:**
- saves screen space (we're not limited in space)
- can support huge list of options (we have 5 options at most)

**Dropdown disadvantages:**
- hides all possible options so users might not discover some functionality of the program. Decreases discoverability of the app.
- has higher interaction cost than buttons because you need to click the dropdown first to open the list then select your desired option which is a total of 2 micro interactions. While with buttons is just need 1 interaction click the button ... much easier
- interaction cost for mobile is even worse.

**Button advantages:**
- users can see all options at once meaning they have a low chance of not seeing a certain functionality
- buttons needs just a single click.

**Button disadvantages**
- its not ergonomical to list more than 5 options. Too much choice and clutter decreasing readability and decision making if >5 buttons are present.

So, I think in our case using buttons instead of dropdown will be much more efficient from a component usability standpoint. It will improve the discoverability, usability, and accessibility.

**Comment by bitcoinuser** [comment]
Hi @odb366, thanks for the post. 

1- Forget about the idea os refund button as I wrote here: https://github.com/LN-Zap/zap-desktop/issues/250#issuecomment-361405867
I think if we have a pending refunding, we can filter this clicking on pending button. I just think that transactions that is used to fund a channel or that is received from close channel, should have the icon on left explaining it. (The same way how request icon works). 

2- Question: Do you think we should keep the dropdown menu to filter between LN transactions and On-chain transactions? My opinion is that it's not necessary. 

For me should have only the 5 buttons.

**Comment by odb366** [comment]
Hi @bitcoinuser 

No need for the dropdown because the onchain transactions should be in one of the 5 buttons.

**Comment by JimmyMow** [comment]
The new filters are merged into master. I'm going to close this
