### ISSUE TITLE
Ability to set the TXN priority (fees) on channel open/close events

### ISSUE THREAD

**Issue by brianddk** [LN-Zap/zap-desktop#2526]
From a conversation with @JimmyMow on slack regarding the ability to set TXN fees for channel open and channel close events:

> we actually are about to cut a new release that allows customizing preferences. probably on Monday but, only for regular on-chain transactions. nothing for channels yet unfortunately. feel free to add an issue though and it will get prioritized for the next release the LND API allows for conf target and sats per byte on close channel calls already so should be fairly trivial.

## Detailed Description

When creating a channel the channel initiator ( ?term? ) will have to agree eventually, to pay for at least two on-chain TXNs.  A channel open TXN and a channel close TXN.  Since one of the core mandates of the LN protocol is fee reduction, it would be nice to allow a patient initiator to set these fees very low taking advantage of fee volatility.  Eventually, over possibly hours or days, the open or close TXN will get mined and the channel will either open or close appropriately.  Obviously the standard ***User Warning:*** messaging may be necessary, but it would still be a great feature to have.

This may come with some constraints as the [BOLT003](https://github.com/lightningnetwork/lightning-rfc/blob/master/03-transactions.md#fees) rfc seems to mandate some arbitration between the initiator and counterparty on channel closure priority and fee settlement.  Channel open of course is completely the initiators responsibility to prioritize though.

## Context

Since one of the core mandates of the LN protocol is fee reduction, it would be nice to allow a patient initiator to set these fees very low taking advantage of fee volatility.  Other wallets ([Eclair](https://github.com/ACINQ/eclair-mobile/issues/184) and [lighting-app](https://github.com/lightninglabs/lightning-app/issues/1213)) currently have this feature request pending as well.

## Possible Implementation

As @JimmyMow suggests:

>the LND API allows for conf target and sats per byte on close channel calls already

**Comment by bolatovumar** [comment]
I'm thinking of implementing this and since we already have preferences for target number of blocks for confirmations, could we reuse this preference for channel close transaction also? Or do we want to have separate preferences for lightning channel closing transaction (I'm thinking probably not?).

Also, would we want to let users manually pick the confirmation speed in the final "Close channel" dialog which would override their preferences?

![Screen Shot 2019-08-10 at 1 44 50 PM](https://user-images.githubusercontent.com/1934678/62820973-310cc900-bb75-11e9-9311-969ada454525.png)

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/3681
