### ISSUE TITLE
UI dashboard total satoshis bug

### ISSUE THREAD

**Issue by DrkAlien** [LN-Zap/zap-desktop#2549]
The total available satoshis are incorrect on closing channel event.

I think that on channel close event the amount of satoshis that comes from that transaction are added to the total seen on the dashboard, although it should be somehow calculated differently.

## Steps to Reproduce
0. I funded the wallet with 1 on-chain transaction
1. I opened a channel with ZAP Tech node
2. I send 2 LN transactions with 2 tippin.me accounts (50 sat and 10 sat)
3. I closed the channel
4. The wallet was still open ( this is very important since the balance was ok after wallet restart) and the closing channel transaction was confirmed quickly ( 1-2 mins ).
5. I saw the total sat balance being double ( as well the value in USD since i had one tx only )

## Your Environment

Win 10 Pro

- Zap version: ZAP 0.5.0-beta
- Operating System and version: 

If you have more questions, feel free to ask.

**Comment by bolatovumar** [comment]
I'm seeing something similar but not the same.
I opened a channel on Testnet which was force-closed. I received my channel balance back but for some reason I'm seeing two transactions for identical amounts in the UI instead of one. Also, as a result my balance is more than expected. Also, transaction id for the second (duplicate) transaction points to a transaction that doesn't exist.

First transaction: [https://blockstream.info/testnet/tx/e2496f7d6acd2138acf6866369d10d7946b1d82d6524a9103fcab1d7b59b3bcc](https://blockstream.info/testnet/tx/e2496f7d6acd2138acf6866369d10d7946b1d82d6524a9103fcab1d7b59b3bcc)
Second transaction (duplicate and doesn't actually exist): [https://blockstream.info/testnet/tx/63bad59453ea3a1386589cb995aaf263589a35a720f6a75f6d35cae3ce215160](https://blockstream.info/testnet/tx/63bad59453ea3a1386589cb995aaf263589a35a720f6a75f6d35cae3ce215160)

## Screenshots

Transactions in question:

![Screen Shot 2019-07-31 at 12 03 00 PM](https://user-images.githubusercontent.com/1934678/62199427-263f8080-b38c-11e9-8f15-496f354b939f.png)

### Transaction 1:
![Screen Shot 2019-07-31 at 12 03 09 PM](https://user-images.githubusercontent.com/1934678/62199525-5129d480-b38c-11e9-812d-a3211c7a7ba0.png)
Link: [https://blockstream.info/testnet/tx/e2496f7d6acd2138acf6866369d10d7946b1d82d6524a9103fcab1d7b59b3bcc](https://blockstream.info/testnet/tx/e2496f7d6acd2138acf6866369d10d7946b1d82d6524a9103fcab1d7b59b3bcc)



### Transaction 2:
![Screen Shot 2019-07-31 at 12 03 13 PM](https://user-images.githubusercontent.com/1934678/62199562-5f77f080-b38c-11e9-8cd8-f6dbf5d1236e.png)
Link: [https://blockstream.info/testnet/tx/63bad59453ea3a1386589cb995aaf263589a35a720f6a75f6d35cae3ce215160](https://blockstream.info/testnet/tx/63bad59453ea3a1386589cb995aaf263589a35a720f6a75f6d35cae3ce215160)

**Comment by mrfelton** [comment]
Closing as I believe this is now fixed in master pas part of https://github.com/LN-Zap/zap-desktop/pull/3526
