### ISSUE TITLE
Feature = show history under ZAP

### ISSUE THREAD

**Issue by silver-moose** [LN-Zap/zap-desktop#256]
Will be nice to have a history, expose IND, under TAB under ZAP

**Comment by JimmyMow** [comment]
what do you mean by this?  not sure i understand

**Comment by silver-moose** [comment]
Ability to view the trace, block id, etc. ZAP could replicate IND info under a TAB and add ZAP's transactions.
...BTW, great job. Love it

------------ as example
 lnd: 2018-01-24 14:37:38.570 [INF] RPCS: [listchannels] fetched 0 channels from DB
 lnd: 2018-01-24 14:37:58.638 [INF] RPCS: [listchannels] fetched 0 channels from DB
 lnd: 2018-01-24 14:38:18.600 [INF] RPCS: [listchannels] fetched 0 channels from DB
 lnd: 2018-01-24 14:38:38.592 [INF] RPCS: [listchannels] fetched 0 channels from DB
 lnd: 2018-01-24 14:38:42.392 [INF] BTCN: Processed 1 block in the last 5m3.43s (height 1260298, 2018-01-24 14:38:09 -0500 EST)
 lnd: 2018-01-24 14:38:58.525 [INF] RPCS: [listchannels] fetched 0 channels from DB
 lnd: 2018-01-24 14:39:19.225 [INF] RPCS: [listchannels] fetched 0 channels from DB

**Comment by mrfelton** [comment]
I'm going to close this issue due to inactivity. I don't really understand the original request but I assume the request was to show the lnd logs somewhere within the app - which probably isn't something that we want to do given the intended audience of Zap. You can access lnd logs on the filesystem, and if you really want to see them in the app you can start the app with debugging enabled and see them in the devtools console.
