### ISSUE TITLE
Error: invoice expired. Valid until...

### ISSUE THREAD

**Issue by coever99** [LN-Zap/zap-desktop#262]
No matter what I'm trying to pay, whether it is to my htlc.me wallet or yalls articles I always get the error "Error: invoice expired. Valid until..." Valid until is always the exact time I created the payment address.

**Comment by CryptoChronicus** [comment]
check your system clock maybe? I think that they're only good for 15 minutes from time of creation, so there is a mixup somewhere

**Comment by coever99** [comment]
Yeah, there's something wrong with the automatic system clock setting in Windows 10, manually setting the time fixed the issue. However, not sure if it's a good idea to rely on the system clock

**Comment by CryptoChronicus** [comment]
I typically just set the clock myself, especially on laptops. they can get weird. Particularly for programmers.

**Comment by CryptoChronicus** [comment]
Honestly we should all just start using UTC, everything would be so much easier.

**Comment by mrfelton** [comment]
As I believe the issue here was with your system clock setting I don't think there is much that we can do about this. What would we use use to get the current date if not the system clock? If your system clock is out that would likely affect many more things than just this.

I'm going to close this issue as I think it's out of our control, but please feel free to reopen if you feel otherwise. Thanks.
