### ISSUE TITLE
Add inline auto-suggest for seed words when recovering a wallet

### ISSUE THREAD

**Issue by bolatovumar** [LN-Zap/zap-desktop#2765]
Some wallets auto-suggest you a word when you start typing a word from your seed. You can press tab to accept this word and move to the next word. It would be nice if Zap did this as well.

## Context

1. Seed recovery process will be quicker.
2. Users will be less likely to make errors when typing out their seed.

## Possible Implementation

Show suggested word inline as you start typing it.

**Comment by JimmyMow** [comment]
I don't like this simply for security reasons. Would be the equivalent of auto-suggesting someone's password right?

If you are talking about verifying the seed words, I think we should move to multiple choice. This is what we do with iOS right now. Where instead of Zap asking you to type the `18th` word, we do something like this:

```
What is the 18th word?

17 Hello
18
19 Fair

A. Juice
B. Door
C. Meat
D. Sun
```

Then the user just has to click, instead of type

**Comment by mrfelton** [comment]
@jackmallers I think what he is referring to is the ability to autosuggest/autocomplete words typed by the user based on what they have already typed. Trezor does this and it's actually quite nice.

For example, if I type `a` there are only so many words in the word list that start with the letter `a`. If I type `ab` there are even fewer that start with `ab`... Generally speaking you should only have to type three or four characters of a work in order to narrow down the possible options to only one possibility.

So for example, if I'm trying to type the word `achieve`, and I start by typing the letters `ac` there is only one word in the entire word list that starts with those two characters - `achieve`. So you can save quite a lot of typing by prompting the user to select from one of the possible options based on the characters they have already typed.

**Comment by bolatovumar** [comment]
Yeah, basically what @mrfelton said. I've seen other wallets implement this feature before but can't remember which ones off the top of my head lol.

**Comment by bolatovumar** [comment]
Here is an example from Electrum:
![Screen Shot 2019-08-16 at 8 50 06 PM](https://user-images.githubusercontent.com/1934678/63187399-75153780-c067-11e9-80e3-d5f677c7ffdd.png)

Obviously it wouldn't look exactly the same in Zap as Electrum has one big field into which you type your seed. Zap has individual fields. I would imagine it would look something like this in Zap:

![Screen Shot 2019-08-16 at 8 51 56 PM](https://user-images.githubusercontent.com/1934678/63187547-d6d5a180-c067-11e9-918c-5ab883597429.png)

**Comment by bolatovumar** [comment]
I'm thinking about implementing this but not sure about details.

1. I think we should start the autosuggest only after a user enters at least three characters as there are way too many matches for one or just two characters. Electrum shows a long dropdown if you enter just one or two characters.
![Screen Shot 2019-09-15 at 3 26 57 PM](https://user-images.githubusercontent.com/1934678/64928441-5e304500-d7cd-11e9-8680-9b36b2f4f67e.png)
Not sure if it would be practical to show such a long list when only one character has been entered.

2. I'm not sure how to display the possible matches. Let's say a user entered `app` and there are three matches: `approve`, `apple` and `appear`. I was initially thinking of only showing one suggestion inline like so:
![example](https://user-images.githubusercontent.com/1934678/63187547-d6d5a180-c067-11e9-918c-5ab883597429.png)
I thought it would be cleaner to only show one word inline instead of a dropdown of possible options but now I'm not so sure it's a good idea. Showing only one word inline may make the user think it's the only available option and may confuse some users.

@mrfelton @JimmyMow thoughts about the above and anything else that comes to mind?

**Comment by mrfelton** [comment]
@bolatovumar I don't think we should only show one option if there are multiple possibilities. I think a drop down list is probably the best option and I'd suggest that it should show as soon as the user starts typing. It would automatically narrow down the possible options as the user types. By the time they have entered 3 or 4 characters the list will be narrowed down to a single option in most cases.

We could make the threshold number configurable so that we can test what works best (show immediately, or wait for one or two characters before showing the list.

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/2966 / https://github.com/LN-Zap/zap-desktop/pull/2896
