### ISSUE TITLE
App should not require user to click `next` button when on `Creating Wallet` screen

### ISSUE THREAD

**Issue by mrfelton** [LN-Zap/zap-desktop#2945]
## Description

App should not stall on `Creating Wallet` screen waiting for use input

![image](https://user-images.githubusercontent.com/200251/66414900-9e649b00-e9fa-11e9-874b-78d73f3143b7.png)

## Expected Behavior

App should immediately start creating wallet - should not require user to click next button

## Actual Behavior

Wallet doesn't get created until user clicks next button

## Steps to Reproduce

Create a new wallet and select google as backup provider

## Context

Onboarding

**Comment by bolatovumar** [comment]
This is also an issue when importing an existing wallet.

**Comment by bolatovumar** [comment]
The issue is caused by `UNSAFE_componentWillMount` in `WalletRecover.js`. What was previously a `componentDidMount` was replaced with `UNSAFE_componentWillMount`. Looks like this was done as part of a refactor but I don't know why it had to be changed. Changing it back to `componentDidMount` fixes the issue.

**Comment by mrfelton** [comment]
Lol. Good find!

**Comment by mrfelton** [comment]
Fixed via https://github.com/LN-Zap/zap-desktop/pull/2982

**Comment by mrfelton** [comment]
Fixed via https://github.com/LN-Zap/zap-desktop/pull/2982
