### ISSUE TITLE
Do not allow Receive invoices if no Channels or funds

### ISSUE THREAD

**Issue by LilChange** [LN-Zap/zap-desktop#2981]
The following is something I consider a UX bug. Unlike software bugs which cause a crash, UX bugs cause confusion or user inaction.

## Description

Currently when Zap has zero money in the onchain wallet and zero channels open, it allows users to create `Receive` invoices- why? These invoices can't be paid and fail if the QR Code is scanned in another wallet.

## Possible Fix

- Gray out the `Receive` button and do not allow creating invoices
- Make clicking or hovering on `Receive` show explainer text.

## Steps to Reproduce

- 1. Install Zap wallet and configure using Zap node
- 2. Write down seed, etc...
- 3. Click on "Receive" and generate an invoice
- 4. Invoice is added to activity for the day

## Context

This is likely a confusing experience to new Zap users, especially those not familiar with Bitcoin and Lighting as it is confusing to me as I've been using Bitcoin since 2014 and Lightning for over a year.

## Your Environment

- Zap version: v0.5.3-beta
- Operating System and version: Debian 9

**Comment by mrfelton** [comment]
It's a little presumptuous to assume that someone doesn't want to be able to create an invoice just because they don't currently have liquidity. An invoice can be valid for any amount of time so whilst I might not have liquidity right now I may know that I'm going to be getting some soon and I might know that the invoice will not be paid until some time in the future.

If you try to create an invoice for more than you are currently able to receive we show a warning but do not prevent creation of the invoice.

![image](https://user-images.githubusercontent.com/200251/83939844-52176800-a7e0-11ea-8d9b-4a5da113f864.png)
