### ISSUE TITLE
Minor display issues on macOS

### ISSUE THREAD

**Issue by sohomang** [LN-Zap/zap-desktop#3046]
## Description

Here are some minor display issues. Some of them only appear on smaller screens (< 11") when using a different language than english.

I'm using macOS 10.15, haven't tested on Windows.

## Details
Unasked newlines:
<img width="725" alt="Connect" src="https://user-images.githubusercontent.com/28465517/67443458-425a6300-f605-11e9-9d01-43a767f404b9.png">
<img width="206" alt="Newline" src="https://user-images.githubusercontent.com/28465517/67443512-7c2b6980-f605-11e9-9def-83c8164fe1d1.png">

Could use more spacing / margin:
<img width="771" alt="More padding 2" src="https://user-images.githubusercontent.com/28465517/67443556-ada43500-f605-11e9-9481-899e85a7fc5f.png">
<img width="607" alt="More padding" src="https://user-images.githubusercontent.com/28465517/67443562-b3017f80-f605-11e9-8338-3dd44013cc5f.png">

Unlike other modals, this one's left-aligned here but center-aligned on Zeplin:
<img width="634" alt="Left aligned (not like zeplin)" src="https://user-images.githubusercontent.com/28465517/67443650-ec39ef80-f605-11e9-8c88-97aff6cd15d4.png">

**Comment by bolatovumar** [comment]
I will take a look into these.

**Comment by bolatovumar** [comment]
@sohomang I addressed all issues except for the last one

>Unlike other modals, this one's left-aligned here but center-aligned on Zeplin:

I noticed that these modal headers are center-aligned when they are on a single line and left-aligned when they are on two or more lines. The reason you see it left aligned in your example is because it's on two lines. @mrfelton do you think I should go over all modals with headers of this kind and make them always center-aligned.

Also this:
> Unasked newlines:

I made headers center-aligned here (**Se connecter**, for example). I thought of making it always on a single line and adjust header font size accordingly, however, this is a problem for languages that have long words like German. No way you can fit German headers on a single line.

**Comment by mrfelton** [comment]
> I noticed that these modal headers are center-aligned when they are on a single line and left-aligned when they are on two or more lines. The reason you see it left aligned in your example is because it's on two lines. @mrfelton do you think I should go over all modals with headers of this kind and make them always center-aligned.

@bolatovumar - yes, I think we should make this consistently center aligned.

> I made headers center-aligned here (Se connecter, for example). I thought of making it always on a single line and adjust header font size accordingly, however, this is a problem for languages that have long words like German. No way you can fit German headers on a single line.

Agreed - we only do dynamic font sizing in one place and causes alignment problems of it's own. Better to just the headers IMO.

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/3049
