### ISSUE TITLE
GRPC Error: cannot parse size

### ISSUE THREAD

**Issue by ChrisDoesEverything** [LN-Zap/zap-desktop#341]
Once I start the program I get a message box containing the below message.
https://i.imgur.com/2c2UqJd.jpg

**Comment by PJUllrich** [comment]
Just for searchability, here is the error message in text form (don't include errors as images please)

```
Uncaught Exception:
Error: cannot parse size
    at ClientReadableStream._emitStatusIfDone (/Applications/Zap.app/Contents/Resources/app.asar/node_modules/grpc/src/client.js:255:19)
    at ClientReadableStream._receiveStatus (/Applications/Zap.app/Contents/Resources/app.asar/node_modules/grpc/src/client.js:233:8)
    at /Applications/Zap.app/Contents/Resources/app.asar/node_modules/grpc/src/client.js:705:12
```

**Comment by mrfelton** [comment]
@PJUllrich It looks like you are using the current v0.1.1-beta release from https://github.com/LN-Zap/zap-desktop/releases ?

This version is no longer functional due to recent changes to the lightning network. We will be releasing a new version soon. In the meantime if you would like to get involved in testing you can build/run the latest version of the app from the source code.

**Comment by PJUllrich** [comment]
Yes that is correct! Thanks for the update. I'll run it using the source code instead then. This issue can be closed I think.
