### ISSUE TITLE
lncli version 0.10.99-beta  can not connect to zap wallet

### ISSUE THREAD

**Issue by ac-com-au** [LN-Zap/zap-desktop#3593]
lncli version 0.10.99-beta commit=clock/v1.0.0-171-g8cb1276dbf0bfd9fcbf599df87a43238e599eaac
zap 0.7.0-beta

error message:
Unable to connect to host: Unsupported prerelease version: 0.10.99-beta commit=clock/v1.0.0-171-g8cb1276dbf0bfd9fcbf599df87a43238e599eaac

**Comment by mrfelton** [comment]
What is lncli 0.10.99-beta? Can you try using lncli 0.10.0-beta?

**Comment by ac-com-au** [comment]
can not downgrade to 0.10.2-beta  , but don;t get it why is not allowed to use last beta version of LND  ?

**Comment by mrfelton** [comment]
Can you explain your setup in a little more detail please and what you are trying to do. Thanks.

**Comment by beeforbacon** [comment]
Same. I use the LND 0.10.99-beta and zap does not connect.

**Comment by githorray** [comment]
> What is lncli 0.10.99-beta? Can you try using lncli 0.10.2-beta?

https://github.com/lightningnetwork/lnd/pull/4324

**Comment by mrfelton** [comment]
Hi, zap is compatible with lnd releases up to and including 0.10.3-beta. We do not support the master branch since it can contain contain changes that are largely untested and potentially backwards incompatible.

**Comment by beeforbacon** [comment]
Many interfaces that build on LND allow master including Zeus, RTL, and Zap mobile. Would it be possible to support master branch in the future?

**Comment by mrfelton** [comment]
Supporting lnd master in dev builds is a possibility. Supporting it in our official releases is not really an option.

In fact, we can and sometimes do support lnd master. The problem though is that it can break out from under us at any time. So whilst we can update our master branch today to support lnd's current master branch, it could very easily break tomorrow because lnd change something without warning.

**Comment by beeforbacon** [comment]
I see. The unfortunate thing is for those of us who do use master in our LND stack cannot revert the database to previous version. I never realized this was a large issue, and ZAP is my preferred UI to interact with my node for a long time. I suppose when v0.11.0 rolls around, I will have to think about if I want to use master.

**Comment by mrfelton** [comment]
lnd is a fast moving target.

Zap supports lnd versions back to v0.4.x, and as far far forwards as possible. At a minimum we'll always try to support the latest official release of lnd in our latest official release of Zap.

That implies that the latest release of Zap should continue to work with lnd master until they introduce a breaking change. We generally try to keep our `next` branch up to date with their master branch so that we are ready for when they release a new official release. But of course there can be some time between when they introduce a breaking change and when we are able to adapt zap to be able to support that (along with also supporting versions from before the change).

So, if it's not working in the latest release, or our `master` branch there is a chance that it will work in our `next` branch. If it doesn't yet (as is the case now) we'd usually accept a PR to make it work depending on wether we feel the change in lnd is well enough tested and far forwards enough to be worth us putting the time and effort in supporting.

So we'll update next branch soon enough so that it supports lnd master again (or you can submit a PR that makes the needed changes :))

**Comment by beeforbacon** [comment]
Thank you very much for all you guys do. Looking forward to it.
