### ISSUE TITLE
Why isn't my node pubkey isn't visible on 1ml.com?

### ISSUE THREAD

**Issue by WillWammer** [LN-Zap/zap-desktop#3610]
## Description

My node pubkey isn't visible on 1ml.com. I opened a channel and lightningto.me can't send any receivable bandwidth because as far as it's concerned, I don't exist

## Expected Behavior

The node should pop up and I should be able to get bandwidth

## Actual Behavior

I can't get bandwidth

## Possible Fix

Initially I thought it could've been port forwarding, but I did that, restarted, and still no dice

## Steps to Reproduce

No idea

## Context

I need bandwidth so I can receive sats

## Your Environment

- Zap version: Latest
- Operating System and version: Win10 Pro, 64bit

My node pubkey: 039ee81adab91c62cdc1a80fc052cfa1d7c6193acb72aadc42ad51fd3e906ea858

**Comment by githorray** [comment]
Zap opens private channels by default.

https://github.com/LN-Zap/zap-desktop/blob/c385954df6ee3362d4a7b9a43d0f614b3ca41c6b/renderer/reducers/channels/reducer.js#L425

If you open a public channel, your node will appear on 1ml after a few hours.

**Comment by WillWammer** [comment]
Are you aware of the option to do that in the UI? Because that was my first
thought, and I could never find it.

**Comment by githorray** [comment]
https://github.com/LN-Zap/zap-iOS/issues/241

**Comment by bolatovumar** [comment]
@WillWammer I think @githorray meant the Zap on iOS uses private channels by default. I believe desktop Zap doesn't do that by default. You have to specify you want a private channel explicitly.

**Comment by githorray** [comment]
https://github.com/LN-Zap/zap-iOS/issues/241#issuecomment-527202719

**Comment by mrfelton** [comment]
If you are using zap's build in lnd node then by all channels that you open will be private. We don't provide the option to make public channels when using zap this way since your node will not be a routing node.

Likewise, if you are running the built in lnd node, it won\t show up on 1ml.com because your node is not a routing node and is not broadcasting its address to the network (ie, we don't set `externalIp` since it's not a routing node and likely running behind some kind of home router).
