### ISSUE TITLE
Feature request: restore channel backup

### ISSUE THREAD

**Issue by dexX7** [LN-Zap/zap-desktop#3758]
Hi, on Zap desktop for Windows I would love to see an option to restore channels, which were saved to the hard disk, during seed recovery.

**Comment by Darkbladecr** [comment]
I am on MacOS and I have the same issue. Unable to restore the channels made in the backup, I cannot find any info on how to do this.

**Comment by Darkbladecr** [comment]
@dexX7 I have figured out that you have to manually connect to the Zap desktop LND node with [lncli](https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md) and start the recovery process.

The script I ended up running from the terminal:
```
$ lncli -n testnet --macaroonpath "/Users/username/Library/Application Support/Lnd/data/chain/bitcoin/testnet/admin.macaroon" restorechanbackup --multi_file="channels.backup"
```
With `channels.backup` being the Zap based backup (I used a local backup).

Would be nice if this was included in the documentation of Zap Desktop, or to have the ability to run this command from the Electron app instead of through the command line.

**Comment by mrfelton** [comment]
As above, this is not currently possible from within Zap Desktop (though there is an in development version of this feature hidden behind a feature flag - not advised to use). You are best off using lncli as above.
