### ISSUE TITLE
Possible scam or just a bug? 

### ISSUE THREAD

**Issue by ghost** [LN-Zap/zap-desktop#3789]
I tried to pay someone using funds from my zap wallet. It says the transaction is unconfirmed and when I click on the Transaction ID provided, blockstream says not found. Did I just get scammed?

**Comment by mrfelton** [comment]
> Did I just get scammed?

No. This is free, open source, beta software. Sometimes the lnd node fails to broadcast a transaction even though it records it as having been broadcast in the lnd wallet state. I assume you were able to debug and resolve the issue given the amount of time that has passed since reporting this. You can open a new issue if that's not the case.

Maybe search some of the older issues where people reported issues with broadcasting transactions:

https://github.com/LN-Zap/zap-desktop/issues?q=is%3Aissue+broadcast+is%3Aclosed
