### ISSUE TITLE
Loss of all funds!

### ISSUE THREAD

**Issue by Schiocco** [LN-Zap/zap-desktop#3810]
Hi

Your buggy wallet caused the loss of all funds!
When opening a channel the transaction is NOT FOUND, and the channel never opens.
When restoring via seed from another PC I see the balance, then I sent it to an address and again transaction is NOT FOUND, and pending forever. After those, your shitty wallet showed ZERO balance but I have actually balance!

3 extremely serious bugs that (each one) cause loss of funds.

You are soo poor and amatorial that you did not even create your terms of service page and now users like me can sue you. And I will do it. 
You also keep your website active, and you do not post a single message or popup that alerts users that the software is dead.
Shame on you! I expect a reply from you with a solution on how to recover the funds or I will start legal action.

Regards

**Comment by Schiocco** [comment]
I'm preparing legal actions, and soon I will report your malicious software to GitHub.

**Comment by kewde** [comment]
Hi @Schiocco 

The software you've used is licensed under the MIT license which means that the following applies:

> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

I wish you a lot of luck on recovering your funds.

**Comment by Schiocco** [comment]
This does not apply to your website. It does not include any information about that. 
Also, MIT does not cover criminal behavior like explicitly spreading software that causes loss of funds.

Anyway, I write you here just to alert the other users. I will not disclose further information now. My designated legal firm will get in touch with you soon.

Regards

**Comment by mrfelton** [comment]
This is an open source project. Perhaps if you were to come here and ask your question with in the same spirit, rather than throwing threats of legal action, people here would be more inclined to help you debug the issue that you have unfortunately experienced with this free open source software that has been provided to you for free. I can reassure you that no funds will have been “lost”, that’s not how this works. Perhaps the wallet has run into a synchronisation issue or has hit one of the many bugs in the open source lnd software that underpins it. Please search the previous issues to see how others have solved this problem in the last, and research more about how the software works.

**Comment by Schiocco** [comment]
You are blatantly wrong.

1. LND does not have such critical bugs. It is used by thousands of
transactions daily.
2. Yes, founds can 100% be lost with your buggy software because it never
makes a transaction, the transaction list is not found as well (very
amatorial and serious bug), + recovering the wallet with the seed does not
work (LND sync error) (another very amatorial and serious bug).

I have already tried all methods, but unfortunately, they did not work
because of your buggy software.
Do not try to accuse LND or me of your blatantly and clearly buggy
software.
You are also trying to implicitly state that if I were more friendly, you
would help, but now you do not help? Are you seriously writing this? You
are blackmailing, plus you write a blatant lie because it's by years that
the messages here do not get any help.

I'm shocked you still keep this repository open and even your website
causing trouble for all unfortunate users than try it but I'm happy this
caused you legal issues.
Regards



[image: SCHIOCCO] <https://schiocco.com/>

**Comment by mrfelton** [comment]
Zap desktop is literally a GUI wrapper that sits on top of lnd. It does not store funds and it does not interact with the bitcoin or lightning networks other than acting as a controller of lnd. It is very minimally maintained. It’s running an old version of lnd which has a well known issue whereby sometimes a transaction does not get fully broadcast even though the lnd Wallet state shows the transaction and shows a reduced balance. There is a fix, which is to call the lnd abandontransaction to. - which was specifically added to lnd to help resolve issues like this. Your options may include calling that rpc to abandon the transaction which will reset the wallet state and balance. Or, to import the seed into a different wallet and go through the standard lnd restore procedure. Please research the problem and root cause before attempting any of these options.

**Comment by kewde** [comment]
Also, in the loving spirit of helping others, I'd like you to know that the word "amatorial" means "of, relating to, or inciting sexual love or desire". I believe the word you may have been looking for is "amateurish".
