### ISSUE TITLE
Help to recover Zap in LND

### ISSUE THREAD

**Issue by Den1356** [LN-Zap/zap-desktop#3816]
## Steps to Reproduce

- 1.
- 2.
- 3.
- 4.

## Your Environment

- Zap version:
- Operating System and version:

**Comment by DEH4UK** [comment]
Zap freezes at 94-95% of wallet recovery. Error message: panic: Unable to synchronize wallet to chain: unable to perform wallet recovery: Couldn't retrieve block 00000000000000000005d1dcd91eebc7cce3d7ea2007fc8a80328e5fb6677fa8 from network.I didn't open any LN channels. I have tried different versions of Zap for Windows and Linux OS. I'm not very friendly with Linux. Please tell me how to restore funds step by step through the LND.

**Comment by mrfelton** [comment]
Please can you try with the latest release, https://github.com/LN-Zap/zap-desktop/releases/tag/v0.7.7-beta. Thanks.

**Comment by DEH4UK** [comment]
It turned out to restore the wallet in version Zap 0.6.1 on Windows 10 (using Wi-fi only) on a new device. Then I deleted 0.6.1 without deleting the Zap folder in the App Data/Roaming folder and installed 0.7.7. It generated a new address and all transactions loaded. Thanks for updating the version!
