### ISSUE TITLE
Litecoin Support

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#457]
Currently we don't _really_ support LTC. We only use `Bitcoin` icons, only convert to BTC price, etc. I think it would be valuable if we supported Litecoin and allowed the user to pick which chain they'd like to launch on during onboarding.

**Comment by coblee** [comment]
Agreed! How can we make this a priority? 😀 

Let me know how I can help. I can tweet about it and ask for volunteers to help, but it would be good for it to be easy to figure out what needs to be changed.

**Comment by mrfelton** [comment]
@coblee Currently we connect to BTCd nodes that support Neutrino. Does Litecoin support neutrino?

**Comment by JWWeatherman** [comment]
Please don’t don’t make crap coins a priority.

**Comment by mrfelton** [comment]
@coblee @losh11  I've made a few minor modifications in order to better support Litecoin.

This can be tested here https://github.com/LN-Zap/zap-desktop/pull/1081

This mostly amounts to adding better support for litecoin currency subunits, using dynamic values for things like `chain` and `network` names, and ensuring that our address and invoice parsing can correctly detect litecoin addresses and lightning network payment requests.

This currently only works with connect ting to a remote lnd instance that is on the litecoin chain. We can't support local wallets until litecoin support Neutrino

**Comment by mrfelton** [comment]
Fixed via #1081
