### ISSUE TITLE
main screen does not appear after onboarding 

### ISSUE THREAD

**Issue by mntetai** [LN-Zap/zap-desktop#525]
I have pulled  from master.
When Zap desktop has finished on boarding process  , it is stuck on it's last screen.
Main channel screen dosn't appear even after reload.

OS : win 10 pro
LND : 0.4.2
commit id : 55a261cfe31546aebd52afa9c0b379400d045e31 on master branch 
![onboarding_02_07_2018](https://user-images.githubusercontent.com/1884392/42150283-034631d6-7de2-11e8-88fd-8f0dbcfa250b.png)

**Comment by mrfelton** [comment]
@mntetai please could you test the PR at https://github.com/LN-Zap/zap-desktop/pull/526 which should resolve this issue? Thanks

**Comment by mntetai** [comment]
I found the bug source. 
Chrome dev tools - when it's opened by default on dev environment .
I have commented out this line -  `/*mainWindow.webContents.once('dom-ready', () => {
      mainWindow.openDevTools()
    })*/` lines 80-82 on main.dev.js

**Comment by mntetai** [comment]
I have to check again after you merge to master.
I am not sure that this issue solves it .. 
When I disabled chrome dev tools the app had the correct behaviour ( when sync finished , it opened the main screen ).

**Comment by mrfelton** [comment]
@mntetai I'm pretty sure that is not the cause, although it's possible that it may see as though commenting that out resolves the issue. I have tested your changes to confirm that it doesn't reliably resolve the issue.

The actual issue is a race condition, as described in #526.

The issue only happens sometimes - specifically if when you open the wallet, there is little to no syncing that needs to happen.

ie. If your wallet is already synced, or nearly synced then the issue could happen. If your wallet has some syncing to do (more than a seconds or two's worth) then the issue will not happen.

**Comment by mntetai** [comment]
ok .. merge it then .

**Comment by mntetai** [comment]
I have checked out your branch .
I will have to check it a few times .
So far it looks as if the problem is solved .
But there is still a problem there , I have to close the chrome dev tools to unlock the wallet. ( unlock is disabled if I have dev tools opened .. so there might be another bug hidden there .. )

**Comment by mntetai** [comment]
I have looked in to the mater branch app as well .
In your branch I get the steps events ( react events - changing ui  )
There are no steps events on the master .

**Comment by mntetai** [comment]
Confirmed on win 10 pro
