### ISSUE TITLE
Inaccurate wallet balance after autopilot opens channels

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#579]
When autopilot opens channels for my node it does not refresh my wallet balance. Sometimes I try and send on-chain funds and Zap tells me I don't have sufficient balance. I then look and realize autopilot opened a few channels for me and the funds have gone to opening channels but my wallet balance doesn't reflect that

**Comment by Empact** [comment]
Another issue / possible explanation is that LND doesn't let you spend change until the transaction has a certain amount of depth in the chain (6 blocks, I think?). Would be nice to be able to either open several channels at once in pay-to-many, or issue unconfirmed transactions following from your own change (because unlike incoming funds, it won't disappear if the transaction is reverted in a 51% situation). Both would be changes to LND I believe.
