### ISSUE TITLE
Explain autopilot 60% of funds?

### ISSUE THREAD

**Issue by terencechow** [LN-Zap/zap-desktop#609]
Can you clarify what the below statement means?

`The autopilot automatically creates channels for up to 60% of your on-chain funds.`

Does that mean if I fund this wallet with 1 BTC the autopilot will use 0.6 BTC to open channels? Is this a reasonable amount to open channels with? How much does it cost to open these channels? How much to close and bring them back onchain? Sorry I just want to make sure I know what's going on when I fund a wallet on Zap...

**Comment by mrfelton** [comment]
Hi @terencechow 

Autopilot is a feature of `lnd`. The documentation for it is actually pretty lacking but your basic understanding is correct.

You can get some more insights by reading the comments from the sample lnd config file here https://github.com/lightningnetwork/lnd/blob/0c1b619e53ac88ad53f3a88e5d1129c25ddeaf13/sample-lnd.conf#L251-L265

In terms of fees, there is no way to set the fees directly currently, but I believe it uses a 6 block confirmation target in order to estimate the fee that it automatically applies.

See https://github.com/lightningnetwork/lnd/issues/886 for a discussion about the ability to set the fee rate manually.
