### ISSUE TITLE
lnd not found in path

### ISSUE THREAD

**Issue by mntetai** [LN-Zap/zap-desktop#661]
Os : win10 pro
zap commit id : f159c0776d97986ff7afe3d226167f9a9ff3b593

Steps to reproduce -
Pull from master branch.
Yarn
npm run build
npm run test
npm run dev

![error_enoent_zap_desktop](https://user-images.githubusercontent.com/1884392/43976225-9a6152e2-9ce8-11e8-8214-f93db380dd7c.png)

[error_log_enoent_zap_desktop.txt](https://github.com/LN-Zap/zap-desktop/files/2279156/error_log_enoent_zap_desktop.txt)

**Comment by mrfelton** [comment]
@mntetai in order to help us debug this issue, please could you try the following.

```bash
mkdir /tmp/test
cd /tmp/test
npm init #just hit enter for all the questions
npm install lnd-binary
```

And share the output of the last `npm install` command.

Also, if you cold then:

```
cd /tmp/test/node_modules/lnd-binary
tree -L 2
```

And share the output of the last command (if you don't have `tree` available, just list out the contents of `/tmp/test/node_modules/lnd-binary/vendor/`.

Thanks

**Comment by mntetai** [comment]
I tried "npm install lnd-binary" on the actual installation folder.
I guess that during the initial install I had a problem with the install.
It has installed the lnd binary under "C:\Users\user\Documents\zap-desktop\node_modules\lnd-binary\vendor" which is correct ...
