### ISSUE TITLE
Trying to Sync 2 wallets on two computers

### ISSUE THREAD

**Issue by skcheffy** [LN-Zap/zap-desktop#685]
I have ZAP downloaded on two separate computers.  Used recovery seed to load on second computer but balance and transactions are not the same.

Am I doing something wrong?  One computer is a Mac and one is Linux.

**Comment by mrfelton** [comment]
@skcheffy I don't believe that this is really possible. You can't take a seed from one device and recover it onto another and expect the 2 devices to be in and to remain in sync. You can use the seed to restore on-chain funds, but for funds that are in channels those channels are only maintained on a given device and are not tied to the recovery seed.

Theoretically, you could back up the channel state data in addition to the seed and move that over to another device in order to recover channel balances in addition to on-chain balances, although I don't think you can rely on this as a practical means to keeping multiple devices in sync.

If you want to be able to access one wallet from multiple devices, your best bet would be to set up a single lnd node somewhere, and then connect to it remotely from Zap Desktop using the Zap's `custom` mode. You can connect as many instances of Zap Desktop as you like to a single lnd instance.

**Comment by skcheffy** [comment]
Ok, thank for the response.  That makes sense now.
