### ISSUE TITLE
Blank screen when logging out

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#944]
When clicking log out from one of my wallets I am presented with a blank screen for a few seconds before I get the loading animation

## Expected Behavior

I should be taken to the loading animation directly until the app transfers me to the home screen

## Actual Behavior

I get a blank screen:

<img width="1023" alt="screen shot 2018-11-28 at 11 40 21 am" src="https://user-images.githubusercontent.com/4040039/49170806-9203b200-f302-11e8-89f2-927a481beb96.png">

## Steps to Reproduce

Log out from a Zap wallet on next branch

## Your Environment

Next branch

**Comment by mrfelton** [comment]
@JimmyMow this is because we currently do a full refresh of the browser window when logging out. I do have a plan to improve this, but I'd like to see this come as a later follow up enhancement as it's a fair amount of work to get right - the basic issue is that we need to be able to fully reset the redux state when logging out to ensure stale data from one wallet doesn't bleed into another. As a basic workaround I just do a full refresh which causes the redux state to fully reset.

**Comment by mrfelton** [comment]
I'm my experience, this last's no longer than 1-2 seconds.

**Comment by JimmyMow** [comment]
@mrfelton no worries, makes sense. Let's just keep this open until we address it, whenever that is

**Comment by mrfelton** [comment]
Fix for this in #1017 @JimmyMow

**Comment by mrfelton** [comment]
Fixed via #1017
